services:
  postgres:
    image: postgres:16
    container_name: devflow-postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: willbe
      POSTGRES_DB: devflow

    ports:
      - '5433:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: