services:
  postgres:
    image: postgres:16
    container_name: devflow-postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: willbe
      POSTGRES_DB: devflow

    ports:
      - '5433:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: devflow-redis
    restart: always
    ports:
      - '6379:6379'

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: devflow-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: willbe
      DB_NAME: devflow
      JWT_SECRET: supersecretkey8willbe
      JWT_EXPIRES_IN: 3600
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: